pipeline:
    deps:
      image: jhernandez/chefdk 
      commands:
        - knife cookbook site download  docker -f ./docker.tar.gz
        - mkdir site-cookbooks && mkdir redis-chef
        - tar -xzf docker.tar.gz --directory ./site-cookbooks 
        - tar zcvf chef-solo.tar.gz ./cookbooks ./site-cookbooks
        - mv chef-solo.tar.gz redis-chef/
        - cp template/redis-cluster.template redis-chef/
    s3:
      image: plugins/s3
      acl: public-read
      source: redis-chef/**
      target: /redis-chef
      bucket: jhernandez.me
      strip_prefix: redis-chef/
      secrets: [aws_access_key_id, aws_secret_access_key]
