pipeline:
    deps:
      image: jhernandez/chefdk 
      commands:
        - knife cookbook site download  docker -f ./docker.tar.gz
        - mkdir site-books
        - tar -xzf docker.tar.gz --directory ./site-books
        - tar zcvf chef-solo.tar.gz ./cookbooks ./site-cookbooks 
    s3:
      image: plugins/s3
      acl: public-read
      source: chef-solo.tar.gz
      target: /redis-chef
      bucket: jhernandez.me
      secrets: [aws_access_key_id, aws_secret_access_key]
